# Generated by Django 4.0.4 on 2022-08-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='albulm',
            table='albulm',
        ),
    ]
