# Generated by Django 4.0.4 on 2022-08-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_albulm_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='albulm',
            table=None,
        ),
    ]
